/*
 * Copyright 2021 Nikola Trubitsyn
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package top.threep.plugin.txtic.carbon;

import java.util.HashMap;
import java.util.Map;

public class Languages {
    private static final String APPLICATION_SLASH_JSON = "application/json";
    private static final String APPLICATION_SLASH_N_MINUS_TRIPLES = "application/n-triples";
    private static final String APPLICATION_SLASH_SPARQL_MINUS_QUERY = "application/sparql-query";
    private static final String APPLICATION_SLASH_TYPESCRIPT = "application/typescript";
    private static final String APPLICATION_SLASH_X_MINUS_SH = "application/x-sh";
    private static final String AUTO = "auto";
    private static final String CLOJURE = "clojure";
    private static final String COBOL = "cobol";
    private static final String COFFEESCRIPT = "coffeescript";
    private static final String CRYSTAL = "crystal";
    private static final String CSS = "css";
    private static final String D = "d";
    private static final String DART = "dart";
    private static final String ELIXIR = "elixir";
    private static final String ELM = "elm";
    private static final String ERLANG = "erlang";
    private static final String FORTRAN = "fortran";
    private static final String GHERKIN = "gherkin";
    private static final String GRAPHQL = "graphql";
    private static final String GROOVY = "groovy";
    private static final String HANDLEBARS = "handlebars";
    private static final String HASKELL = "haskell";
    private static final String HTMLMIXED = "htmlmixed";
    private static final String JAVASCRIPT = "javascript";
    private static final String JSX = "jsx";
    private static final String JULIA = "julia";
    private static final String LUA = "lua";
    private static final String MATHEMATICA = "mathematica";
    private static final String MLLIKE = "mllike";
    private static final String NGINX = "nginx";
    private static final String NIM = "nim";
    private static final String PASCAL = "pascal";
    private static final String PERL = "perl";
    private static final String POWERSHELL = "powershell";
    private static final String PYTHON = "python";
    private static final String R = "r";
    private static final String RUBY = "ruby";
    private static final String RUST = "rust";
    private static final String SASS = "sass";
    private static final String SMALLTALK = "smalltalk";
    private static final String SQL = "sql";
    private static final String STYLUS = "stylus";
    private static final String SWIFT = "swift";
    private static final String TCL = "tcl";
    private static final String TEXT_SLASH_TURTLE = "text/turtle";
    private static final String TEXT_SLASH_TYPESCRIPT_MINUS_JSX = "text/typescript-jsx";
    private static final String TEXT_SLASH_X_MINUS_CSHARP = "text/x-csharp";
    private static final String TEXT_SLASH_X_MINUS_CSRC = "text/x-csrc";
    private static final String TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC = "text/x-c++src";
    private static final String TEXT_SLASH_X_MINUS_DIFF = "text/x-diff";
    private static final String TEXT_SLASH_X_MINUS_GO = "text/x-go";
    private static final String TEXT_SLASH_X_MINUS_JAVA = "text/x-java";
    private static final String TEXT_SLASH_X_MINUS_KOTLIN = "text/x-kotlin";
    private static final String TEXT_SLASH_X_MINUS_OCTAVE = "text/x-octave";
    private static final String TEXT_SLASH_X_MINUS_PHP = "text/x-php";
    private static final String TEXT_SLASH_X_MINUS_SCALA = "text/x-scala";
    private static final String TEXT_SLASH_X_MINUS_TWIG = "text/x-twig";
    private static final String TOML = "toml";
    private static final String VERILOG = "verilog";
    private static final String VHDL = "vhdl";
    private static final String VUE = "vue";
    private static final String XQUERY = "xquery";
    private static final String YAML = "yaml";
    private static final Map<String, String> mapping = new HashMap<>();

    static {
        mapping.put("_coffee", COFFEESCRIPT);
        mapping.put("_js", JAVASCRIPT);
        mapping.put("adml", HTMLMIXED);
        mapping.put("admx", HTMLMIXED);
        mapping.put("adp", TCL);
        mapping.put("al", PERL);
        mapping.put("ant", HTMLMIXED);
        mapping.put("app.src", ERLANG);
        mapping.put("avsc", APPLICATION_SLASH_JSON);
        mapping.put("aw", TEXT_SLASH_X_MINUS_PHP);
        mapping.put("axml", HTMLMIXED);
        mapping.put("bones", JAVASCRIPT);
        mapping.put("boot", CLOJURE);
        mapping.put("builder", RUBY);
        mapping.put("builds", HTMLMIXED);
        mapping.put("c", TEXT_SLASH_X_MINUS_CSRC);
        mapping.put("c++", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("cake", TEXT_SLASH_X_MINUS_CSHARP);
        mapping.put("cake", COFFEESCRIPT);
        mapping.put("cats", TEXT_SLASH_X_MINUS_CSRC);
        mapping.put("cbl", COBOL);
        mapping.put("cc", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("ccp", COBOL);
        mapping.put("ccproj", HTMLMIXED);
        mapping.put("ccxml", HTMLMIXED);
        mapping.put("cdf", MATHEMATICA);
        mapping.put("cgi", PERL);
        mapping.put("cgi", PYTHON);
        mapping.put("cjs", JAVASCRIPT);
        mapping.put("cjsx", COFFEESCRIPT);
        mapping.put("cl2", CLOJURE);
        mapping.put("clixml", HTMLMIXED);
        mapping.put("clj", CLOJURE);
        mapping.put("cljc", CLOJURE);
        mapping.put("cljs", CLOJURE);
        mapping.put("cljs.hl", CLOJURE);
        mapping.put("cljscm", CLOJURE);
        mapping.put("cljx", CLOJURE);
        mapping.put("cob", COBOL);
        mapping.put("cobol", COBOL);
        mapping.put("coffee", COFFEESCRIPT);
        mapping.put("cp", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("cpp", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("cproject", HTMLMIXED);
        mapping.put("cpy", COBOL);
        mapping.put("cql", SQL);
        mapping.put("cr", CRYSTAL);
        mapping.put("cs", TEXT_SLASH_X_MINUS_CSHARP);
        mapping.put("cs", SMALLTALK);
        mapping.put("cscfg", HTMLMIXED);
        mapping.put("csdef", HTMLMIXED);
        mapping.put("csl", HTMLMIXED);
        mapping.put("csproj", HTMLMIXED);
        mapping.put("css", CSS);
        mapping.put("csx", TEXT_SLASH_X_MINUS_CSHARP);
        mapping.put("ct", HTMLMIXED);
        mapping.put("ctp", TEXT_SLASH_X_MINUS_PHP);
        mapping.put("cxx", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("d", D);
        mapping.put("dart", DART);
        mapping.put("ddl", SQL);
        mapping.put("depproj", HTMLMIXED);
        mapping.put("dfm", PASCAL);
        mapping.put("di", D);
        mapping.put("diff", TEXT_SLASH_X_MINUS_DIFF);
        mapping.put("dita", HTMLMIXED);
        mapping.put("ditamap", HTMLMIXED);
        mapping.put("ditaval", HTMLMIXED);
        mapping.put("dll.config", HTMLMIXED);
        mapping.put("dotsettings", HTMLMIXED);
        mapping.put("dpr", PASCAL);
        mapping.put("eliom", MLLIKE);
        mapping.put("eliomi", MLLIKE);
        mapping.put("elm", ELM);
        mapping.put("erl", ERLANG);
        mapping.put("es", ERLANG);
        mapping.put("es", JAVASCRIPT);
        mapping.put("es6", JAVASCRIPT);
        mapping.put("escript", ERLANG);
        mapping.put("ex", ELIXIR);
        mapping.put("exs", ELIXIR);
        mapping.put("eye", RUBY);
        mapping.put("f", FORTRAN);
        mapping.put("f77", FORTRAN);
        mapping.put("fcgi", LUA);
        mapping.put("fcgi", PERL);
        mapping.put("fcgi", TEXT_SLASH_X_MINUS_PHP);
        mapping.put("fcgi", PYTHON);
        mapping.put("fcgi", RUBY);
        mapping.put("feature", GHERKIN);
        mapping.put("filters", HTMLMIXED);
        mapping.put("for", FORTRAN);
        mapping.put("fpp", FORTRAN);
        mapping.put("frag", JAVASCRIPT);
        mapping.put("fs", MLLIKE);
        mapping.put("fsi", MLLIKE);
        mapping.put("fsproj", HTMLMIXED);
        mapping.put("fsx", MLLIKE);
        mapping.put("fxml", HTMLMIXED);
        mapping.put("gemspec", RUBY);
        mapping.put("geojson", APPLICATION_SLASH_JSON);
        mapping.put("glade", HTMLMIXED);
        mapping.put("gltf", APPLICATION_SLASH_JSON);
        mapping.put("gml", HTMLMIXED);
        mapping.put("gmx", HTMLMIXED);
        mapping.put("go", TEXT_SLASH_X_MINUS_GO);
        mapping.put("god", RUBY);
        mapping.put("gql", GRAPHQL);
        mapping.put("graphql", GRAPHQL);
        mapping.put("graphqls", GRAPHQL);
        mapping.put("groovy", GROOVY);
        mapping.put("grt", GROOVY);
        mapping.put("grxml", HTMLMIXED);
        mapping.put("gs", JAVASCRIPT);
        mapping.put("gtpl", GROOVY);
        mapping.put("gvy", GROOVY);
        mapping.put("gyp", PYTHON);
        mapping.put("gypi", PYTHON);
        mapping.put("h", TEXT_SLASH_X_MINUS_CSRC);
        mapping.put("h", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("h++", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("handlebars", HANDLEBARS);
        mapping.put("har", APPLICATION_SLASH_JSON);
        mapping.put("hbs", HANDLEBARS);
        mapping.put("hh", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("hic", CLOJURE);
        mapping.put("hpp", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("hrl", ERLANG);
        mapping.put("hs", HASKELL);
        mapping.put("hs-boot", HASKELL);
        mapping.put("hsc", HASKELL);
        mapping.put("htm", HTMLMIXED);
        mapping.put("html", HTMLMIXED);
        mapping.put("html.hl", HTMLMIXED);
        mapping.put("hxx", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("ice", APPLICATION_SLASH_JSON);
        mapping.put("iced", COFFEESCRIPT);
        mapping.put("idc", TEXT_SLASH_X_MINUS_CSRC);
        mapping.put("iml", HTMLMIXED);
        mapping.put("inc", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("inc", HTMLMIXED);
        mapping.put("inc", PASCAL);
        mapping.put("inc", TEXT_SLASH_X_MINUS_PHP);
        mapping.put("inc", SQL);
        mapping.put("inl", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("ino", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("ipp", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("ivy", HTMLMIXED);
        mapping.put("jake", JAVASCRIPT);
        mapping.put("java", TEXT_SLASH_X_MINUS_JAVA);
        mapping.put("jbuilder", RUBY);
        mapping.put("jelly", HTMLMIXED);
        mapping.put("jl", JULIA);
        mapping.put("js", JAVASCRIPT);
        mapping.put("jsb", JAVASCRIPT);
        mapping.put("jscad", JAVASCRIPT);
        mapping.put("jsfl", JAVASCRIPT);
        mapping.put("jsm", JAVASCRIPT);
        mapping.put("json", APPLICATION_SLASH_JSON);
        mapping.put("json", APPLICATION_SLASH_JSON);
        mapping.put("JSON-tmLanguage", APPLICATION_SLASH_JSON);
        mapping.put("jsonl", APPLICATION_SLASH_JSON);
        mapping.put("jsproj", HTMLMIXED);
        mapping.put("jss", JAVASCRIPT);
        mapping.put("jsx", JSX);
        mapping.put("kml", HTMLMIXED);
        mapping.put("kojo", TEXT_SLASH_X_MINUS_SCALA);
        mapping.put("kt", TEXT_SLASH_X_MINUS_KOTLIN);
        mapping.put("ktm", TEXT_SLASH_X_MINUS_KOTLIN);
        mapping.put("kts", TEXT_SLASH_X_MINUS_KOTLIN);
        mapping.put("launch", HTMLMIXED);
        mapping.put("linq", TEXT_SLASH_X_MINUS_CSHARP);
        mapping.put("lmi", PYTHON);
        mapping.put("lpr", PASCAL);
        mapping.put("lua", LUA);
        mapping.put("m", MATHEMATICA);
        mapping.put("m", TEXT_SLASH_X_MINUS_OCTAVE);
        mapping.put("ma", MATHEMATICA);
        mapping.put("map", APPLICATION_SLASH_JSON);
        mapping.put("mathematica", MATHEMATICA);
        mapping.put("matlab", TEXT_SLASH_X_MINUS_OCTAVE);
        mapping.put("mcmeta", APPLICATION_SLASH_JSON);
        mapping.put("mdpolicy", HTMLMIXED);
        mapping.put("mir", YAML);
        mapping.put("mjml", HTMLMIXED);
        mapping.put("mjs", JAVASCRIPT);
        mapping.put("ml", MLLIKE);
        mapping.put("ml4", MLLIKE);
        mapping.put("mli", MLLIKE);
        mapping.put("mll", MLLIKE);
        mapping.put("mly", MLLIKE);
        mapping.put("mm", HTMLMIXED);
        mapping.put("mod", HTMLMIXED);
        mapping.put("mspec", RUBY);
        mapping.put("mt", MATHEMATICA);
        mapping.put("mxml", HTMLMIXED);
        mapping.put("mysql", SQL);
        mapping.put("natvis", HTMLMIXED);
        mapping.put("nb", MATHEMATICA);
        mapping.put("nbp", MATHEMATICA);
        mapping.put("ncl", HTMLMIXED);
        mapping.put("ndproj", HTMLMIXED);
        mapping.put("nginxconf", NGINX);
        mapping.put("nim", NIM);
        mapping.put("nim.cfg", NIM);
        mapping.put("nimble", NIM);
        mapping.put("nimrod", NIM);
        mapping.put("nims", NIM);
        mapping.put("njs", JAVASCRIPT);
        mapping.put("nproj", HTMLMIXED);
        mapping.put("nse", LUA);
        mapping.put("nt", APPLICATION_SLASH_N_MINUS_TRIPLES);
        mapping.put("nuspec", HTMLMIXED);
        mapping.put("odd", HTMLMIXED);
        mapping.put("osm", HTMLMIXED);
        mapping.put("p8", LUA);
        mapping.put("pac", JAVASCRIPT);
        mapping.put("pas", PASCAL);
        mapping.put("pascal", PASCAL);
        mapping.put("patch", TEXT_SLASH_X_MINUS_DIFF);
        mapping.put("pd_lua", LUA);
        mapping.put("perl", PERL);
        mapping.put("ph", PERL);
        mapping.put("php", TEXT_SLASH_X_MINUS_PHP);
        mapping.put("php3", TEXT_SLASH_X_MINUS_PHP);
        mapping.put("php4", TEXT_SLASH_X_MINUS_PHP);
        mapping.put("php5", TEXT_SLASH_X_MINUS_PHP);
        mapping.put("phps", TEXT_SLASH_X_MINUS_PHP);
        mapping.put("phpt", TEXT_SLASH_X_MINUS_PHP);
        mapping.put("pkgproj", HTMLMIXED);
        mapping.put("pl", PERL);
        mapping.put("pluginspec", HTMLMIXED);
        mapping.put("pluginspec", RUBY);
        mapping.put("plx", PERL);
        mapping.put("pm", PERL);
        mapping.put("podspec", RUBY);
        mapping.put("pp", PASCAL);
        mapping.put("prc", SQL);
        mapping.put("proj", HTMLMIXED);
        mapping.put("props", HTMLMIXED);
        mapping.put("ps1", POWERSHELL);
        mapping.put("ps1xml", HTMLMIXED);
        mapping.put("psc1", HTMLMIXED);
        mapping.put("psd1", POWERSHELL);
        mapping.put("psgi", PERL);
        mapping.put("psm1", POWERSHELL);
        mapping.put("pt", HTMLMIXED);
        mapping.put("py", PYTHON);
        mapping.put("py3", PYTHON);
        mapping.put("pyde", PYTHON);
        mapping.put("pyi", PYTHON);
        mapping.put("pyp", PYTHON);
        mapping.put("pyt", PYTHON);
        mapping.put("pyw", PYTHON);
        mapping.put("r", R);
        mapping.put("rabl", RUBY);
        mapping.put("rake", RUBY);
        mapping.put("rb", RUBY);
        mapping.put("rbi", RUBY);
        mapping.put("rbuild", RUBY);
        mapping.put("rbw", RUBY);
        mapping.put("rbx", RUBY);
        mapping.put("rbxs", LUA);
        mapping.put("rd", R);
        mapping.put("rdf", HTMLMIXED);
        mapping.put("re", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("reek", YAML);
        mapping.put("resx", HTMLMIXED);
        mapping.put("rockspec", LUA);
        mapping.put("rpy", PYTHON);
        mapping.put("rq", APPLICATION_SLASH_SPARQL_MINUS_QUERY);
        mapping.put("rq", APPLICATION_SLASH_SPARQL_MINUS_QUERY);
        mapping.put("rs", RUST);
        mapping.put("rs.in", RUST);
        mapping.put("rss", HTMLMIXED);
        mapping.put("rsx", R);
        mapping.put("ru", RUBY);
        mapping.put("ruby", RUBY);
        mapping.put("rviz", YAML);
        mapping.put("sass", SASS);
        mapping.put("sbt", TEXT_SLASH_X_MINUS_SCALA);
        mapping.put("sc", TEXT_SLASH_X_MINUS_SCALA);
        mapping.put("scala", TEXT_SLASH_X_MINUS_SCALA);
        mapping.put("sch", HTMLMIXED);
        mapping.put("scxml", HTMLMIXED);
        mapping.put("sfproj", HTMLMIXED);
        mapping.put("sh", APPLICATION_SLASH_X_MINUS_SH);
        mapping.put("shproj", HTMLMIXED);
        mapping.put("sjs", JAVASCRIPT);
        mapping.put("smk", PYTHON);
        mapping.put("sparql", APPLICATION_SLASH_SPARQL_MINUS_QUERY);
        mapping.put("spec", PYTHON);
        mapping.put("spec", RUBY);
        mapping.put("sql", SQL);
        mapping.put("srdf", HTMLMIXED);
        mapping.put("ssjs", JAVASCRIPT);
        mapping.put("st", HTMLMIXED);
        mapping.put("st", SMALLTALK);
        mapping.put("storyboard", HTMLMIXED);
        mapping.put("styl", STYLUS);
        mapping.put("sublime-snippet", HTMLMIXED);
        mapping.put("sublime-syntax", YAML);
        mapping.put("swift", SWIFT);
        mapping.put("syntax", YAML);
        mapping.put("t", PERL);
        mapping.put("tab", SQL);
        mapping.put("tac", PYTHON);
        mapping.put("targets", HTMLMIXED);
        mapping.put("tcc", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("tcl", TCL);
        mapping.put("tfstate", APPLICATION_SLASH_JSON);
        mapping.put("tfstate.backup", APPLICATION_SLASH_JSON);
        mapping.put("thor", RUBY);
        mapping.put("tm", TCL);
        mapping.put("tml", HTMLMIXED);
        mapping.put("toml", TOML);
        mapping.put("topojson", APPLICATION_SLASH_JSON);
        mapping.put("tpp", TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC);
        mapping.put("ts", HTMLMIXED);
        mapping.put("ts", APPLICATION_SLASH_TYPESCRIPT);
        mapping.put("tsx", HTMLMIXED);
        mapping.put("tsx", TEXT_SLASH_TYPESCRIPT_MINUS_JSX);
        mapping.put("ttl", TEXT_SLASH_TURTLE);
        mapping.put("ttl", TEXT_SLASH_TURTLE);
        mapping.put("twig", TEXT_SLASH_X_MINUS_TWIG);
        mapping.put("udf", SQL);
        mapping.put("ui", HTMLMIXED);
        mapping.put("urdf", HTMLMIXED);
        mapping.put("ux", HTMLMIXED);
        mapping.put("v", VERILOG);
        mapping.put("vbproj", HTMLMIXED);
        mapping.put("vcxproj", HTMLMIXED);
        mapping.put("veo", VERILOG);
        mapping.put("vhd", VHDL);
        mapping.put("vhdl", VHDL);
        mapping.put("vhf", VHDL);
        mapping.put("vhi", VHDL);
        mapping.put("vho", VHDL);
        mapping.put("vhost", NGINX);
        mapping.put("vhs", VHDL);
        mapping.put("vht", VHDL);
        mapping.put("vhw", VHDL);
        mapping.put("viw", SQL);
        mapping.put("vsixmanifest", HTMLMIXED);
        mapping.put("vssettings", HTMLMIXED);
        mapping.put("vstemplate", HTMLMIXED);
        mapping.put("vue", VUE);
        mapping.put("vxml", HTMLMIXED);
        mapping.put("watchr", RUBY);
        mapping.put("webapp", APPLICATION_SLASH_JSON);
        mapping.put("webmanifest", APPLICATION_SLASH_JSON);
        mapping.put("wixproj", HTMLMIXED);
        mapping.put("wl", MATHEMATICA);
        mapping.put("wlt", MATHEMATICA);
        mapping.put("wlua", LUA);
        mapping.put("workflow", HTMLMIXED);
        mapping.put("wsdl", HTMLMIXED);
        mapping.put("wsf", HTMLMIXED);
        mapping.put("wsgi", PYTHON);
        mapping.put("wxi", HTMLMIXED);
        mapping.put("wxl", HTMLMIXED);
        mapping.put("wxs", HTMLMIXED);
        mapping.put("x3d", HTMLMIXED);
        mapping.put("xacro", HTMLMIXED);
        mapping.put("xaml", HTMLMIXED);
        mapping.put("xht", HTMLMIXED);
        mapping.put("xhtml", HTMLMIXED);
        mapping.put("xib", HTMLMIXED);
        mapping.put("xlf", HTMLMIXED);
        mapping.put("xliff", HTMLMIXED);
        mapping.put("xmi", HTMLMIXED);
        mapping.put("xml", HTMLMIXED);
        mapping.put("xml.dist", HTMLMIXED);
        mapping.put("xproj", HTMLMIXED);
        mapping.put("xpy", PYTHON);
        mapping.put("xq", XQUERY);
        mapping.put("xql", XQUERY);
        mapping.put("xqm", XQUERY);
        mapping.put("xquery", XQUERY);
        mapping.put("xqy", XQUERY);
        mapping.put("xrl", ERLANG);
        mapping.put("xsd", HTMLMIXED);
        mapping.put("xsjs", JAVASCRIPT);
        mapping.put("xsjslib", JAVASCRIPT);
        mapping.put("xspec", HTMLMIXED);
        mapping.put("xul", HTMLMIXED);
        mapping.put("yaml", YAML);
        mapping.put("yaml-tmlanguage", YAML);
        mapping.put("yaml.sed", YAML);
        mapping.put("yml", YAML);
        mapping.put("yml.mysql", YAML);
        mapping.put("yrl", ERLANG);
        mapping.put("yy", APPLICATION_SLASH_JSON);
        mapping.put("yyp", APPLICATION_SLASH_JSON);
        mapping.put("zcml", HTMLMIXED);
    }

    public static String forExtension(String extension) {
        if (extension == null) {
            return AUTO;
        }
        return mapping.getOrDefault(extension, AUTO);
    }
}
